# Generated by Django 3.2.8 on 2021-11-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
