# Generated by Django 3.2.8 on 2021-11-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockroom', '0004_alter_bookinstance_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='price',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('Hard', 'Hard cover'), ('Soft', 'Soft cover')], default='Soft', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
    ]
