# Generated by Django 3.2.8 on 2021-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_orderhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name_plural': 'History of orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='book_id',
        ),
        migrations.AddField(
            model_name='order',
            name='book_id',
            field=models.ManyToManyField(to='shop.Book'),
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='book_id',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='book_id',
            field=models.ManyToManyField(to='shop.Book'),
        ),
    ]
