# Generated by Django 3.2.8 on 2021-11-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(default='https://placekitten.com/200/300'),
        ),
    ]
